<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Company.Portal.Web</RootNamespace>
    <AssemblyName>Company.Portal.Web</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Company.Portal.Invoices/Company.Portal.Invoices.csproj" />
    <ProjectReference Include="../Company.Portal.Cms/Company.Portal.Cms.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.12" />
  </ItemGroup>
</Project>
